name: kd
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - rdkit
  - pip
  - pip:
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.10.11
    - aiosignal==1.3.1
    - alembic==1.14.1
    - altair==5.4.1
    - async-timeout==5.0.1
    - attrs==25.3.0
    - blinker==1.8.2
    - cachetools==5.5.2
    - certifi==2022.12.7
    - charset-normalizer==2.1.1
    - click==8.1.8
    - colorama==0.4.6
    - colorlog==6.9.0
    - contourpy==1.1.1
    - cycler==0.12.1
    - dgl==0.9.1
    - filelock==3.13.1
    - fonttools==4.57.0
    - frozenlist==1.5.0
    - fsspec==2025.3.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - greenlet==3.1.1
    - huggingface-hub==0.30.2
    - idna==3.4
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - jinja2==3.1.4
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - kaleido==0.2.1
    - kiwisolver==1.4.7
    - lightning-utilities==0.11.9
    - mako==1.3.10
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.1.0
    - narwhals==1.39.0
    - networkx==3.0
    - numpy==1.24.1
    - optuna==4.3.0
    - packaging==24.2
    - pandas==2.0.3
    - pillow==10.2.0
    - pkgutil-resolve-name==1.3.10
    - plotly==6.1.2
    - propcache==0.2.0
    - protobuf==5.29.4
    - psutil==7.0.0
    - pyarrow==17.0.0
    - pydeck==0.9.1
    - pygments==2.19.1
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.2
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.28.1
    - rich==13.9.4
    - rpds-py==0.20.1
    - safetensors==0.5.3
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - seaborn==0.13.2
    - six==1.17.0
    - smmap==5.0.2
    - sqlalchemy==2.0.41
    - streamlit==1.40.1
    - sympy==1.13.1
    - tenacity==9.0.0
    - threadpoolctl==3.5.0
    - tokenizers==0.20.3
    - toml==0.10.2
    - torch==2.0.0
    - torch-geometric==2.6.1
    - torchaudio==2.0.1
    - torchdata==0.6.0
    - torchmetrics==1.5.2
    - torchvision==0.15.1
    - tornado==6.4.2
    - tqdm==4.67.1
    - transformers==4.46.3
    - typing-extensions==4.12.2
    - tzdata==2025.2
    - urllib3==1.26.13
    - watchdog==4.0.2
    - yarl==1.15.2
    - zipp==3.20.2
